name: Build and Release (PyInstaller Matrix)

on:
  push:
    branches:
      - main
      - canary

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          # tkinter installation sur Linux (et éventuellement sur macOS si besoin)
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update || true
            sudo apt-get install -y python3-tk || true
          fi
        shell: bash

      - name: Build with console
        run: |
          pyinstaller --onefile main.py --name app_with_console_${{ runner.os }}

      - name: Build without console
        run: |
          pyinstaller --onefile --noconsole main.py --name app_no_console_${{ runner.os }}

      - name: Prepare release assets
        run: |
          mkdir release
          cp dist/app_with_console_${{ runner.os }}* release/
          cp dist/app_no_console_${{ runner.os }}* release/
        shell: bash

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }} - ${{ github.sha }} (${{ matrix.os }})
          tag_name: build-${{ github.run_number }}
          prerelease: ${{ github.ref_name == 'canary' }}
          files: |
            release/app_with_console_${{ runner.os }}*
            release/app_no_console_${{ runner.os }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
